name: Mi-UnLuac Nightly Build
on: workflow_dispatch

jobs:
  jarbuild:
    name: Build Jar
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 2
    - name: Get commit hash
      shell: bash
      run: |
        git checkout HEAD^
        calculatedSha=$(git rev-parse --short ${{ github.sha }})
        echo "COMMIT_SHORT_SHA=$calculatedSha" >> $GITHUB_ENV
    - name: Setup JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '9.0.4'
    - name: Build
      run: |
        mkdir build
        javac -d build -sourcepath src  src/unluac/*.java
        jar -cfm build/unluac.jar src/META-INF/MANIFEST.MF -C build  .
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: Mi-Unluac-${{ github.ref_name }}-${{ env.COMMIT_SHORT_SHA }}.jar
        path: build/unluac.jar
